version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=booking_pass

    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/:rw
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ./scripts/postgres_always.sh:/postgres_always.sh:row
      - ./scripts/postgres_run.sh:/usr/local/bin/postgres_run.sh:row
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "psql -U booking_user -d booking -c 'SELECT 1;'"]
      interval: 60s
      timeout: 5s
      retries: 3
    command: postgres_run.sh

  redis:
    container_name: redis
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    restart: on-failure